import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import {
  JSXElementConstructor,
  ReactElement,
  ReactFragment,
  ReactPortal,
  useEffect,
} from "react";
import CommonApi from "../api/common.api";
import { Category } from "../configuration/Interfaces";
import styles from "../styles/Home.module.css";

const Home: NextPage = ({ data }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a href="/login" className={styles.card}>
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
          <ul className={styles.card}>
            {data.categories.map((data: Category) => (
              <li>{data.name}</li>
            ))}
          </ul>
          <ul className={styles.card}>
            {data.animes.results.map((data: any) => (
              <li>{data.title}</li>
            ))}
          </ul>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export async function getServerSideProps() {
  // Fetch data from external API

  const categories = await CommonApi.getCategories();
  const animes = await CommonApi.getAnimes();
  const data = {
    categories,
    animes,
  };

  // Pass data to the page via props
  return { props: { data } };
}

export default Home;
